### PR TITLE
Skylight rework

### PR DESCRIPTION
**Pull request by Foghrye4**
Seem to fix random black spots under cliffs appearing sometimes.
Opinion on this?

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
That code needs major redesign currentlym it needs to be called before population without specifically generating any new cubes for it.

It also needs to update sunlight in all loaded cubes below the one being updated. Not sure if your code handles it. Would you be able to explain how your code works?

**Comment by Niko-sk2x** [comment]
initializeSkyLight also needs to be gone. LightPropagator needs some rework too to make it actuall have decent performance.

**Comment by Foghrye4** [comment]
It update skylight for a single cube only assuming that all sky light...
Ow. I forgot to spread light to loaded cubes nearby.
Anyway. ...assuming that all sky light values in cube equal to 0. First it sets light values in temporary array equal to 15 according heightmap and fills encoded local coordinates in array for pass 0. After that it iterate thru that array and spread values 14 to all sides to same array and add encoded coordinate for pass 1 and so on.
After that it uses array to finally modify sky light values of a cube.

**Comment by Niko-sk2x** [comment]
you basically reimplemented LightPropagator here. Your code is basically equivalent to giving iterable with all BlockPos in the cube to LightPropagator. And starting with assumption that light = 0 isnb't a good idea

**Comment by Foghrye4** [comment]
Aha. It just was a little easier for me to reimplemented LightPropagator instead of understanding how it works. (And why it is not)

**Comment by Niko-sk2x** [comment]
a lot of the work my previous code did was filtering out the BlockPos that didn't need updates. Sicne I'm going to redeign the code anyway, I'm not merging it.

**Pull request closed without merging**
