### PR TITLE
Fixing nether portal spawn below y=0

### PR DESCRIPTION
**Pull request by Foghrye4**
I fixed my own MalisisCore issue by eliminating whole CubicChunks folder and cloning it again.

Issue #161.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
Latest Mixin version supports proper zero zero comparison with `@ModifyConstant` which will allow to replace all of those `getY` Regirects with `ModifyConstant`, ~~there should be examples of it in `core/column-as-mixin` branch~~ I didn't actually use it there, it didn't exist at the time I wrote most of the code. While I'm probably not going to change all the existing code at once yet, it would be better to write new code using this feature.

You just need to update to newer version of mixin.

**Comment by Foghrye4** [comment]
This is not working:
```	
@ModifyConstant(method = "<init>", constant = @Constant(intValue = 0, ordinal = 0), require = 1)
	private int portalSizeClassInitReplace0(int posY, World worldIn, BlockPos origin, EnumFacing.Axis axis) {
		return ((ICubicWorld)worldIn).getMinHeight();
	}
```

Neither is this:
```	
@ModifyConstant(method = "<init>", constant = @Constant(intValue = 0), require = 1)
	private int portalSizeClassInitReplace0(int posY, World worldIn, BlockPos origin, EnumFacing.Axis axis) {
		return ((ICubicWorld)worldIn).getMinHeight();
	}
```

This throw an error (mixin failed):
```	
@ModifyConstant(method = "<init>", constant = @Constant(intValue = 0, ordinal = 1), require = 1)
	private int portalSizeClassInitReplace0(int posY, World worldIn, BlockPos origin, EnumFacing.Axis axis) {
		return ((ICubicWorld)worldIn).getMinHeight();
	}
```

Got any thoughts?

**Comment by Niko-sk2x** [comment]
You need to update to mixin 0.6.8, and use special option, like this:
```java
@ModifyConstant(method = "<init>", constant = @Constant(intValue = 0, ordinal = 0, expandZeroConditions = Constant.Condition.GREATER_THAN_ZERO), require = 1)
private int portalSizeClassInitReplace0(int posY, World worldIn, BlockPos origin, EnumFacing.Axis axis) {
    return ((ICubicWorld)worldIn).getMinHeight();
}
```
Just change `GREATER_THAN_ZERO` to whatever you need. You can also put more than one condition, like `{Constant.Condition.GREATER_THAN_ZERO, Constant.Condition.GREATER_THAN_OR_EQUAL_TO_ZERO}`

**Comment by Foghrye4** [comment]
Done.

**Comment by Niko-sk2x** [comment]
Currently there is still an issue with MalisisCore dependency, and I need to find a way to fix it.

**Pull request merged**
