### PR TITLE
Fixed conduits generating infinite cubes Y.

### PR DESCRIPTION
**Pull request by OverInfrared**
Fixed conduit changing load cubes from world height to 256 (placeholder)

### CODE REVIEW

**Comment by Cyclonit** [comment]
@Barteks2x, @NotStirred, we weren't 100% sure if this is the right way to go. Conduits try to affect all players from the bottom to the top of the world. This obviously doesn't work in CC. This PR changes the behaviour to only affect players in a 256 blocks tall column around the conduit.

**Comment by muzikbike** [comment]
so I assume this is 256 blocks above and another 256 blocks below the conduit, in order to mimic vanilla behaviour as closely as possible?

**Comment by NotStirred** [comment]
Provided this works I think this is the way to go yeah; I would like to test whether the range is as muzikbike suggests as that would make most sense.

**Comment by NotStirred** [comment]
Perhaps a better approach would be to prevent conduits from loading cubes at all, as the cubes are not needed unless a player is in them anyway.

**Comment by NotStirred** [comment]
This does nothing and the issue still exists. I believe conduits are the underwater damaging TileEntity. Could also target BeaconTileEntity x)

**Comment by NotStirred** [comment]
Merged in c7f324b96ddedd38729f0054cb1c3fa467d0bb32 and I refuse to fix the git mess that is Github

**Comment by Niko-sk2x** [comment]
This assumes chunk load distance of at least 8. It should check if the chunks are loaded before accessing them.

**Comment by NotStirred** [comment]
It already does this. It uses AbstractChunkProvider#getChunk passing in `false` as the `load` arg
as can be seen in `World#getEntitiesWithinAABB(Class, AxisAlignedBB, Predicate)`

**Comment by NotStirred** [comment]
It will generate the chunk however

**Comment by Barteks2x** [comment]
But it doesn't check for cubes.

**Pull request closed without merging**
