### PR TITLE
Are we ready?

### PR DESCRIPTION
**Pull request by Foghrye4**

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
It's going to randomly crash currently if you remove that workaround. It's rare but it happens.

**Comment by DaMatrix** [comment]
What causes the crash? I'd like very much to remove it, even if it means I have to go fix up other things.

**Comment by Niko-sk2x** [comment]
`LightPropagator` being broken in a fundamental way. It can be fixed but doing so exposes even more bugs in `FirstLightProcessor`.

Basically, when unspreading light (decreasing light values) it's possible for it to somehow end up adding a not yet updated light source that isn't in the expected block range to the queue with all of the 15 blocks distance to spread. And when it spreads all those 15 blocks, it may run into cube that isn't in the `FastCubeBlockAccess`. Which either crashes or does something stupid (more likely does something stupid, it rarely crashes. Especially when the situation described isn't very common).

The fix? It can either be hacked around by making unspreading light keep track of blocks to spread count, or by complete redesign of `LightPropagator`, `FastCubeBlockAccess`, potentially changes to `LightUpdateQueue`, redesign of some parts of `LightingManager` and some parts of code that touch it, and `FirstLightProcessor`.

The core idea in my new design being that light spreading won't need to touch neighbor cubes, and instead will add 6 boolean flags per cube: a per-cube-wall `edgeNeedsUpdate` flag.

When the neighbor cube isn't loaded, light values will be assumed to be 0, and no `setLight` will be done on them (this will be handled in `FastCubeBlockAccess`) with additional checks for that situation in `LightPropagator` to avoid potemtially adding blocks known to be in unloaded cubes to the queue. When attempting to `getLight` or `setLight` in such unloaded cubes, the relevant edge flags will be set true.

Then when a cube is loaded, it would check the 6 flags **and those 6 flags of each currently loaded neighbor cube** and check if there are lighting inconsistencies along the edges, and add them to update queue. Since there are no additional cubes loaded needed - this can be done without any queueing and waiting until  the needed cubes are loaded, maybe even from the cube loader thread (!).

Another advantage would be faster world generation and less chunk GC when generating terrain. Currently lighting is the one reason for loading 5x5x5 cube area just to generate one cube. That's 125 cubes just to generate one of them. Thios could be reduced to 3x3x3 = 27 cubes needed for population after this change making world generation seemingly much faster.

**Comment by Niko-sk2x** [comment]
Note: if someone is able to - I welcome PRs actually implementing it. It's not easy and it's a lot of work IO may not have the time for anytime soon.

**Pull request closed without merging**
