### PR TITLE
[1.17] New Colours for loading screen

### PR DESCRIPTION
**Pull request by NotStirred**

### CODE REVIEW

**Comment by CursedFlames** [comment]
in-game color key when

**Comment by NotStirred** [comment]
you said you'd do it so...

**Comment by CursedFlames** [comment]
dang okay then

**Comment by CursedFlames** [comment]
you're welcome 😎

**Comment by NotStirred** [comment]
there was something else I wanted to do before I merged, but I've now forgotten, if I don't remember in a few days I'll just merge

**Comment by NotStirred** [comment]
ready for merge

**Pull request merged**
