### PR TITLE
[1.16] Fixed pistons not pushing past Y level 0.

### PR DESCRIPTION
**Pull request by OverInfrared**
Fixed pistons not pushing past Y level 0.

### CODE REVIEW

**Comment by muzikbike** [comment]
I'd advise removing this fix for the 1.16.2 version, since it's supposedly fixed in vanilla. https://bugs.mojang.com/browse/MC-69876

**Comment by Cyclonit** [comment]
We don't know if they actually removed the height limit or if they merely fixed it for 0-256. We'll have to wait and see if this still applies.

**Comment by muzikbike** [comment]
Yes, behaviour in 1.16.2 appears different now. Can someone test to see if this pull still fixes the issue?

**Comment by NotStirred** [comment]
Closing due to dropping 1.15/16, and 1.17 vanilla is expected to deal with this

**Pull request closed without merging**
