### PR TITLE
Small tweaks and fixes

### PR DESCRIPTION
**Pull request by sirsavary**
Hello, I'm interested in helping with this project. I've started by making some small tweaks and fixing a bug with a call to string.format.

Looking forward to helping with getting CubicChunks completely stable, it's the perfect mod for my server and its community.

### CODE REVIEW

**Comment by Barteks2x** [comment]
Please fix your tabs/spaces usage. And try to avoid/limit formatting changes if possible. If you can, use formatting settings I provided [here](https://github.com/Barteks2x/CubicChunks/blob/master/idea16-formatting-settings.xml)

**Comment by sirsavary** [comment]
Oops, will take care of that.

**Comment by Barteks2x** [comment]
@sirsavary If you are still interested in helping with this project, can you send me PM on minecraftforums? I could explain in more details what are my plans, what needs to be done, and maybe a bit about how things work. I don't think github is good place for this kind of discussion.

**Comment by sirsavary** [comment]
Will do! I was actually thinking the same thing, wanted more information but didn't want to make an issue to ask basic questions.

**Comment by Cyclonit** [comment]
Mind sharing your ideas with the general public/me? I'd be very interested as well.

**Comment by Barteks2x** [comment]
@Cyclonit So you are back? Many of my plans are simply issues waiting to be closed, maybe I will write  what I was going to write on the wiki (and finally update it). And since there was no place to discuss things, I created one on gitter (you should be both invited).

**Pull request merged**
