### PR TITLE
Optimisation test

### PR DESCRIPTION
**Pull request by Foghrye4**
Thats what I did.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
Does it include #238 and #237?

**Comment by Foghrye4** [comment]
@Barteks2x yes. But I absolutely not sure if those PR actually help reduce lag.  I've got a noticeable speed gain only when I had CubicEntitySpawner rewritten.

**Comment by Niko-sk2x** [comment]
Could you submit separate PR with just that part rewritten, and the parts you inlined extracted into methods where possible?

**Comment by Foghrye4** [comment]
@Barteks2x yes.

**Comment by Niko-sk2x** [comment]
So what should I do with this PR? Close it or will you work on making it mergable?

**Comment by Foghrye4** [comment]
Cubic chunks are working fast enough now. Probably I could move a random block tick to cubes as well. For that I need to inject to WorldServer.updateBlocks() and rewrite it. Thats probably an only thing that could fasten server tick, because in vanilla to create random tick we iterate thru chunks (columns) and then thru extended block storages. We could use existing cube iterator and skip some instructions (although we still need to iterate thru columns for weather effects).

Should I prepare PR for that?

**Comment by Niko-sk2x** [comment]
Sure but as always make it optional.

**Pull request closed without merging**
