### PR TITLE
Launch cube watch event when player added to cube

### PR DESCRIPTION
**Pull request by Foghrye4**
Since I want to use that event to spawn entities I would like to see it here.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
It would probably be more useful when done like in [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/server/management/PlayerChunkMapEntry.java.patch) patch, so that the watch event is fired when a cube is sent to the player.

**Comment by Foghrye4** [comment]
Here: https://github.com/Foghrye4/CubicChunks/blob/8c660f27f19d21e93fbf81a695de79b222915670/src/main/java/cubicchunks/server/CubeWatcher.java#L205 ?

**Comment by Niko-sk2x** [comment]
Yes

**Comment by Foghrye4** [comment]
Updated.

**Pull request merged**
