### PR TITLE
Remove opacity bit

### PR DESCRIPTION
**Pull request by Cyclonit**
Implements #139

### CODE REVIEW

**Review by Niko-sk2x — CHANGES_REQUESTED** [review]
Good that someone decided to do that, even when it's not a proiority here. It will just allow to use fill 32-bit int height range. Just a few things:
 * I initially planned using `long`s to pack 2 segments into one entry, if done properly this would mean no way to have inconsistencies. You do't need to implement it here, but it would be great to see that.
 * Since the structure is now much more fragile some additional sanity checks would be good (in the form of asserts to avoid slowing down it doen in non-dev) - for example that after each operation the amout of segments in total is reasonable (correct parity, depending on implementation it's either always even or always odd). Another possible check would be making sure that after each oprtation the opacities of neighbor (up/down) segments didn't change but this may be tricker to implement as assert.
 * Tests for extreme heights

**Comment by Cyclonit** [comment]
I'd rather only add sanity checks and refrain from packing values into longs. Packing introduces additional operations. Whilst these operations are binary operations, and thus very fast, they are additional operations we don't need.

**Comment by Niko-sk2x** [comment]
I agree here, that's why it may be better to just add these sanity checks for total amount of entries and that neighbors inferred opacity bit didn;t change. If done as asserts, it wouldn't affect performance at all.

**Review by Niko-sk2x — APPROVED** [review]

**Comment by Niko-sk2x** [comment]
That seems ok. I don't see why expteme heights could break there, so leaving it as it. I'm curious now to see what happens if I remove height limits...

**Pull request merged**
