### PR TITLE
Mixin config

### PR DESCRIPTION
**Pull request by Foghrye4**
This commit cause TestWorldServerMixin test fail. But I have no idea why. There is nothing uncommon in fml-client-latest.log
I hope you could give me a hint, Barteks2x.

Mixin config works fine.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
I would need to build it myself and see how the test fails.

**Comment by Foghrye4** [comment]
https://pastebin.com/cw17XVz6

**Comment by Foghrye4** [comment]
It seems that when mixin launched from test, it ignore plugin restrictions.

**Comment by Niko-sk2x** [comment]
Hm... it's trying to load both Collision one and SlowCollision one.

**Comment by Niko-sk2x** [comment]
Could you always do the slow one, keeping it as is (without moving to separate file), and set the fast one to higher priority so it overwrites completely the slow one?

**Comment by Foghrye4** [comment]
Yes, I can. But this would be a workaround.
Log shows, that Mixin config is loaded (check 'CubicChunksMixinConfig' in log), a question is why it does not skip loading one of a Mixin classes?

There is a log output for function `shouldApplyMixin(...)`, but nothing is in a log. `shouldApplyMixin(...)` is never called.

**Comment by Niko-sk2x** [comment]
It's still a better way to do it, I will investogate why the problem occurs anyway but you probably should change it. That way there is no chance of conflicts based on config

**Comment by Foghrye4** [comment]
Yep, that works.

**Comment by Niko-sk2x** [comment]
Could you leave the old version as a commit here too, so the old way is visible in commit history? (it may be mixin/LWTS issue, and I want the code that causes it to be available)

**Comment by Foghrye4** [comment]
No. But I can recreate old state (so I did).

**Comment by Niko-sk2x** [comment]
Is it ready to merge now?

**Comment by Foghrye4** [comment]
Yes.

**Comment by Niko-sk2x** [comment]
There is your cause:
```
java.lang.NullPointerException
	at net.minecraftforge.common.config.Configuration.runConfiguration(Configuration.java:121)
	at net.minecraftforge.common.config.Configuration.<init>(Configuration.java:151)
	at net.minecraftforge.common.config.Configuration.<init>(Configuration.java:111)
	at cubicchunks.asm.CubicChunksMixinConfig.onLoad(CubicChunksMixinConfig.java:52)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:428)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.selectConfigs(MixinTransformer.java:693)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:666)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:647)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.spongepowered.lwts.runner.LaunchWrapperTestRunner.loadTestClass(LaunchWrapperTestRunner.java:79)
	at org.spongepowered.lwts.runner.LaunchWrapperTestRunner.<init>(LaunchWrapperTestRunner.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by Niko-sk2x** [comment]
@Foghrye4 can you fix it?

**Comment by Foghrye4** [comment]
@Barteks2x Only way to build FMLInjectionData to load Forge config properly is to launch FMLLaunchHandler. But to launch it I need LaunchClassLoader. But when I tried to `mock` it, `SecurityException` is thrown. Dead end?

**Comment by Niko-sk2x** [comment]
When running tests with LWTS `LaunchClassLoader` should be the classloader used to load any Minecraft classes. Get instance of it that way.

**Comment by Foghrye4** [comment]
```
    @Before
    public void setUp() throws IOException {
        MinecraftEnvironment.init();
        MinecraftServer server = MinecraftEnvironment.createFakeServer();
        FMLLaunchHandler.configureForServerLaunch((LaunchClassLoader) MinecraftServer.class.getClassLoader(), new FMLTweaker());
        ISaveHandler mockSaveHandler =
                new AnvilSaveHandler(folder.newFolder("save"), "world", false, new DataFixer(512));
        WorldType cubicChunksType = new FlatCubicWorldType();
        WorldSettings settings = new WorldSettings(0, GameType.SURVIVAL, false, false, cubicChunksType);
        WorldInfo worldInfo = new WorldInfo(settings, "test");
        this.world = (ICubicWorldServer) new WorldServer(server, mockSaveHandler, worldInfo, 0, new Profiler());
    }
```
Result in:
```
        Caused by: java.lang.SecurityException at TestWorldServerMixin.java:79

cubicchunks.TestWorldServerMixin > testWorldMinHeightVanillaCompatibility FAILED
    java.lang.RuntimeException at TestWorldServerMixin.java:79
        Caused by: java.lang.SecurityException at TestWorldServerMixin.java:79
java.lang.SecurityException: Cannot replace the FML security manager
        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:54)
        at java.lang.System.setSecurityManager0(System.java:300)
        at java.lang.System.setSecurityManager(System.java:291)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:77)
```

**Comment by Niko-sk2x** [comment]
Could you try passing null for FML tweaker as a workaround?

**Comment by Foghrye4** [comment]
Null cause NPL.
I tried to mock it, but now it is:
```
java.lang.LinkageError: net/minecraftforge/fml/common/launcher/FMLTweaker
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:220)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:100)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:85)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47)
	at cubicchunks.TestWorldServerMixin.setUp(TestWorldServerMixin.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Foghrye4** [comment]
Here is what I did: https://pastebin.com/shzknwZc
But without priority there is still mixin collision. Where did you get that crash log which you showed me?

**Comment by Niko-sk2x** [comment]
I ran the test in intellij (you need to add `-Dlwts.tweaker=cubicchunks.tweaker.MixinTweakerServer` jvm argument)

**Comment by Foghrye4** [comment]
Uhum. Same exception.

**Comment by Foghrye4** [comment]
```        assertNotNull(FMLInjectionData.data()[6]);```
launched before ```MinecraftEnvironment.init();``` does not throw any exceptions.

**Comment by Foghrye4** [comment]
Adding this code in 
```
public class CubicChunksMixinConfig implements IMixinConfigPlugin {

    private Configuration configuration;
    @Nonnull
    public static Logger LOGGER = LogManager.getLogger("CubicChunksMixinConfig");

    @Override
    public void onLoad(String mixinPackage) {
        for (Method method : FMLInjectionData.class.getDeclaredMethods()) {
            if (method.getName().contains("build")) {
                method.setAccessible(true);
                try {
                    method.invoke(null, new File("."), (LaunchClassLoader) MinecraftServer.class.getClassLoader());
                } catch (IllegalAccessException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (IllegalArgumentException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (InvocationTargetException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        }
```
fix issue. But does it really worth it?

**Comment by Niko-sk2x** [comment]
For now just keep it with non-working configuration plugin leaving a clear comment that it doesn't work in tests

**Comment by Foghrye4** [comment]
We cannot compile Cubic Chunks if test failed. I hope you mean that you want to leave this PR as it is (with two colliding mixins with different priority).

PS: I just realise that you DO mean that.

**Comment by Niko-sk2x** [comment]
Yes, keep the priorities different.

**Comment by Niko-sk2x** [comment]
So in that case it's ready to merge?

**Comment by Foghrye4** [comment]
Yes. I have add a comment.

**Comment by Niko-sk2x** [comment]
What did you break here? I twas working before you added the comment.

**Comment by Foghrye4** [comment]
I had no idea.

**Comment by Foghrye4** [comment]
Maybe I should add that hack.

**Comment by Niko-sk2x** [comment]
Or just remove that test for now... it's broken anyway and only causes issues. It has never caught an actual real issue.

**Comment by Foghrye4** [comment]
@Barteks2x its because I made static `config` field from CubicChunks.class public. It should be fine in #261 now.

**Pull request merged**
