### PR TITLE
Catch all possible cases of custom block state implementations

### PR DESCRIPTION
**Pull request by Foghrye4**
Ok, I screwed one more time with collision optimization code.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
I don't really like ths idea of catching exception here, but whatever. It's disabled by default.

**Comment by Foghrye4** [comment]
@Barteks2x please take a proper look at this part: https://github.com/OpenCubicChunks/CubicChunks/pull/390/files#diff-704e4293dbc7fa85270f49d1c104e101R188

**Comment by Niko-sk2x** [comment]
I've seen that. I think I forgot to change that.

**Comment by Foghrye4** [comment]
What if instead of "try-catch" I will filter a list of vanilla blocks by checking if they extends only vanilla classes? I really like this optimization - it gives a great TPS gain when a lot of mobs are around player.

**Comment by Niko-sk2x** [comment]
This would probably be better as part of something like FormFix and not CC. Or some other separate mod. I will try to separate vanilla optimizations into it's own mod at some point.

**Comment by Foghrye4** [comment]
Ok.

**Pull request closed without merging**
