### PR TITLE
Allow teleporting past Y= +/- 20 million

### PR DESCRIPTION
**Pull request by Setadokalo**

### CODE REVIEW

**Review by CorgiTaco — COMMENTED** [review]
Im not sure if an overwrite is the right move tbh.

Maybe redirecting the 4 usages of this method would be better. Each usage does have access to a level in its class. Maybe check against if the world is cubic, if so, use the implementation of your overwrite instead.

**Comment by Setadokalo** [comment]
it's such a tiny method - a one liner - and the other methods in this mixin already use `@Override` for similar methods. I did forget the cubic world check for sure though, I'll add that now.

**Comment by Setadokalo** [comment]
Actually, I can't check for `isCubic()`, since the method is static.

**Comment by CorgiTaco** [comment]
This is why I suggested the redirect of all 4 usages of this method :P

**Review by CorgiTaco — APPROVED** [review]
MMM yes this is a very good PR, 10/10 quality, would definitely accept PR from you again. Very good, thank you for your contribution

**Comment by CursedFlames** [comment]
Thank you Corgi very cool

**Comment by Niko-sk2x** [comment]
Doesn't need isCubic checks. This is for checking absolute possible limits, so it's fine if it's beyond the limits of the actual world you are in.

**Pull request merged**
