### PR TITLE
Configurable fast entity spawner

### PR DESCRIPTION
**Pull request by Foghrye4**
I still want to reanimate that idea as configurable (false by default) option.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
CI Build failed

**Comment by Niko-sk2x** [comment]
Is it actually still faster if you let it run until it reaches entity count limit (test total tick time)?

**Comment by Niko-sk2x** [comment]
I also can't find anything that would limit entities per chunk.

And specifically what I want to know - once it reaches entity limit it should be fast. But is it still fast soon before reaching that limit?

How does it behave if all you have is small island in the void? Does it spawn a lot of entities there without a limit?

**Comment by Foghrye4** [comment]
@Barteks2x how you suggest to measure that?

**Comment by Niko-sk2x** [comment]
`/forge tps`

**Comment by Foghrye4** [comment]
Without fast entity spawner average tps - 14.3
With fast entity spawner average tps - 20.
Test conditions: XYZ: 0 645 0
World ocean level 640
World type - custom cubic.
(I tried to spawn squids but did not saw any)
Other mods: Iblis, Dungeon generator.

**Comment by Niko-sk2x** [comment]
It also shows tick time. Which is the value I was interested in.

How does the tick time change as more mobs are spawned?
How does it work when all you have is small island in the air with no other blocks at night (skyblock)?
What is the tick time when you are in completely empty space that has a huge platform above you so it has no place to spawn mobs in but it's all dark? (superflat with only one layer)
What if you add some blocks to eah of those cubes (glass maybe) so none of them are empty but none have blocks mobs can spawn on?

If it's actually faster in all those cases with many render distance values (4, 8, 12, 16) then I can merge it.

**Comment by Foghrye4** [comment]
>How does the tick time change as more mobs are spawned?

Its became longer. Both spawners does not reach limit because mobs constantly de-spawn.

>How does it work when all you have is small island in the air with no other blocks at night (skyblock)?

Its quite hard to make such noise settings for me so there would be that sky islands.

>What is the tick time when you are in completely empty space that has a huge platform above you so it has no place to spawn mobs in but it's all dark? (superflat with only one layer)

Test conditions: Flat, one layer (stone), night.
Mobs are still spawned with both spawners
Tick time old spawner: 21 ms
Tick time new spawner: 16 ms

>What if you add some blocks to eah of those cubes (glass maybe) so none of them are empty but none have blocks mobs can spawn on?

Test conditions: Flat, two layers (glass x1/stone x1), night.
No mobs are  spawned with both spawners
Tick time old spawner: 20.8 ms
Tick time new spawner: 14.6 ms

**Comment by Niko-sk2x** [comment]
> Its quite hard to make such noise settings for me so there would be that sky islands.

So make void world and make an island yourself

> Test conditions: Flat, one layer (stone), night.
> Mobs are still spawned with both spawners
> Tick time old spawner: 21 ms
> Tick time new spawner: 16 ms

So *where* do they spawn? At least in day time.

> Test conditions: Flat, two layers (glass x1/stone x1), night.
> No mobs are spawned with both spawners
> Tick time old spawner: 20.8 ms
> Tick time new spawner: 14.6 ms


That's not what I meant. But whatever. I doubt your code checks if cube is empty.

**Comment by Foghrye4** [comment]
>So make void world and make an island yourself

Done.

>So where do they spawn? At least in day time.

On an island. Island quickly filled with mobs with old spawner and slightly slower with a new spawner.

>That's not what I meant. But whatever. I doubt your code checks if cube is empty.

There is no differences in checks between old and new spawner. We already have a conversation about that, see #244 
A difference between #244 and this is that this (new) spawner is disabled by default and can be enabled/disabled in a middle of a game with config option.

Imgur

**Pull request merged**
