### PR TITLE
Unload queue

### PR DESCRIPTION
**Pull request by Foghrye4**
Is that what you mean by 

> Unload packets also should be queued the same way as chunk data packets.

?

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
There is this one which you made equivalent of https://github.com/Foghrye4/CubicChunks/blob/af6587ed218794079e7712f442a62e4a0069cf4b/src/main/java/cubicchunks/server/PlayerCubeMap.java#L157

and there is this one https://github.com/Foghrye4/CubicChunks/blob/af6587ed218794079e7712f442a62e4a0069cf4b/src/main/java/cubicchunks/server/PlayerCubeMap.java#L201
which is what needs to be added for unloading.

**Comment by Foghrye4** [comment]
@Barteks2x check new version.

**Comment by Niko-sk2x** [comment]
...what?

What you did here makes no sense.

There alreasy was the sorted `cubesToSendToPlayers` list, which is the one that may need sorting. This one is a list of cube watchers and is updated dynamically, and only limited amount of them is processed per tick.

Then there is the `cubesToSend` **multimap**. And it's there and done that way for a good reason:

When each cube is sent individually in a packet, the compression of them is really bad because each packet is compressed separately. So there is much more data sent over network than in vanilla. A way to fix this, is to send many cubes in one packet.

But `PlayerChunkMap` is designed in a way that makes it impossible to easily put multiple cubes into one packet (I tried). So a way to workaround this issue, was to create **another** cubesToSend field, which for each player effectively stores a set of cubes to send. The amount if cubes added to it is exactly the same as the amount of cubes that would be sent in that tick if it didn't exist **because cubes are added to it in the same place that normally sends them**. So all of them can be sent in a single tick. You made it another layer of rate-limiting, which actually may cause more issues than it solves.

What I suspected was the issue - which now that I try to explain it, seems to be complete nonsense - is that somehow the cubes are being unloaded immediately after being sent because of the additional queue (again, no idea how that would make sense, but it did at the time I thought of it). But adding `UnloadCubes` would still be a good idea.

I also know that the issue with some cubes not being sent to player has been introduced either together with sending multiple cubes per packet, or when I [introduced this enum](https://github.com/Foghrye4/CubicChunks/blob/084cb4c02f3334551c5514bb127d7629b072eb4e/src/main/java/cubicchunks/server/CubeWatcher.java#L374-L376). Probably the multiple-cubes part, because I noticed that right then the `MultiplayerChunkCache` no longer matched the extected value.

So the issue may require forther debugging to be fixed, most likely in the form of very detailed logging.

**Comment by Foghrye4** [comment]
I didn't get it. Whatever.

**Pull request closed without merging**
