### PR TITLE
Interface naming cleanup

### PR DESCRIPTION
**Pull request by Cyclonit**
- Renamed all interfaces to not use the preceding "I" in their name, as this is not Java naming convention.
- Removed ICubePrimer as this interface was not used and appears useless to me.
- Renamed IHeightMap to SurfaceTracker.
- Cleaned up variables of type SurfaceTracker to no longer be called "opacityIndex", "index" or similar.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
I assume you tested that it actually runs?

**Comment by Cyclonit** [comment]
Both "gradlew build" and "gradlew test" finished without troubles. Generating all three world types and running around in them works, so does breaking and placing blocks.

**Comment by ZombieHDGaming** [comment]
Hey there,
if you don't mind me asking, why was this PR accepted with the interface updates? This would break all compatibility with most mods that have added it. I know in my case, I work with my team on DimDoors and literally added compatibility for this just under 14 hours ago and was broken already from this PR. I'm not saying it's a bad thing, but this will result in many people asking why this was changed and people running to complain. Sure it may not be within Java naming conventions, but this kinda goes against Forge modding conventions with classes and interfaces. Just figured this should be brought to your attention.

Cheers,
Zombie

**Comment by Niko-sk2x** [comment]
You do bring up some good points here and for now i will revert it and reapply together with moving some interfaces to actual api package. I wikl also explain the reasons i did it. Keep in mind that what you have now is not an api. You are directly using cubic chunks internals. 

Forge using that naming was the reason i started it that way. But i currently have regionlib library which is completely separated from Minecraft and i want to move to standard Java naming in it. And i want consistency across my projects. And I'm planning to separate some other parts of the mod into non Minecraft libraries too (mainly some of the lighting code and some parts of world generation if its possible). Using the nonstandard naming isn't a good idea for more general Java libraries. 

I wanted it done now precisely because i see mods try to be compatible by directly using the internals and it would better be done now when few mods depend on it than a year later when it would break more mods.

**Pull request merged**
