### PR TITLE
Heightmap update event

### PR DESCRIPTION
**Pull request by Foghrye4**

### CODE REVIEW

**Review by Cyclonit — COMMENTED** [review]
Is it normal for Forge events to be posted before the change occurred? Otherwise I think you should post it afterwars and put both the old and the new opacity in the event.

**Review by Niko-sk2x — CHANGES_REQUESTED** [review]
Tabs vs spaces

**Comment by Niko-sk2x** [comment]
Forge events generally are posted before the change occurs and you get the old and wheat will be new value.

**Comment by Foghrye4** [comment]
After some investigation I realize that this PR will not serve a purposes necessary for Setadokalos' map mod, because whenever client receive cube data, height-map is updated via raw `setData` method.
I wonder if posting a same event here: https://github.com/OpenCubicChunks/CubicChunks/pull/381/files#diff-a7f898f67d1a3540043e54e5ed72a2a7L134
wont affect a performance of Minecraft?

**Comment by Niko-sk2x** [comment]
After closer look at this, I don';t think posting an event on every block set is a good idea.

**Comment by Foghrye4** [comment]
Ok, I will make a ClientCubeLoad event later instead.

**Pull request closed without merging**
