### PR TITLE
Remove client light updates

### PR DESCRIPTION
**Pull request by Foghrye4**
?

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
This is and will always be needed.

**Comment by Foghrye4** [comment]
What for? Everything looks absolutely fine without it.

**Comment by Niko-sk2x** [comment]
More explanation: I'm only sending actual light data changes from FirstLightProcessor, because updating it clientside wopuld be too much of a performance hit and it's not expected to be normal occurrence in already explored world.

But normal block changes caused by players are expected to be frequent and vanilla doesn't send light updates for those, it just does them clientside. Since it's usually not going to be a big performance hit we can do it clientside just like vanilla.

**Comment by Niko-sk2x** [comment]
This particular thing is for when there are 2+ players and one changes something very high up and the other needs to see shadow updates.

**Comment by Foghrye4** [comment]
It is a big performance hit.
screenshot from 2018-01-07 00-29-05
Thats a reason I asked you.

**Comment by Niko-sk2x** [comment]
Hm... it shouldn't be especially not if there is just one player. Find what causes this.

**Comment by Niko-sk2x** [comment]
specifially find what schedules so many light updates clientside. If it comes from network, find what sends the packets. If it's block updates, what causes these block updates?

**Comment by Niko-sk2x** [comment]
Disabling what you did is just a hack that hides the issue.

**Comment by Foghrye4** [comment]
On cube generation populator call `world.setBlockState()`. Which cause lighting manager to call `sendHeightMapUpdate()`.

Snapshot I made here is generated while I slowly moving towards not generated cubes.

**Comment by Niko-sk2x** [comment]
Hm... that makes things harder. With this part disabled, very tall trees could break things. I will attempt to handle it in my rewrite by changing some global world lighting mode to send the light updates to client.

**Comment by Niko-sk2x** [comment]
For now, comment it out and leave comment linking to this PR.

**Comment by Niko-sk2x** [comment]
And add a link that leads here for full explanation.

**Pull request merged**
