### PR TITLE
Fast iterable XYZ map

### PR DESCRIPTION
**Pull request by Foghrye4**
To compare performance was launched such test at init stage of Cubic chunks:
```
      XYZMap<AddressableTest> map1 = new XYZMap<AddressableTest>(0.7f,8000);
        XYZMap2<AddressableTest> map2 = new XYZMap2<AddressableTest>(0.7f,8000);
        Random rnd = new Random();
        long time1 = System.currentTimeMillis();
        for(int i=0;i<80000;i++){
            int x = rnd.nextInt();
            int y = rnd.nextInt();
            int z = rnd.nextInt();
            map1.put(new AddressableTest(x,y,z,x+";"+y+";"+z));
        }
        long time2 = System.currentTimeMillis();
        for(int i=0;i<80000;i++){
            int x = rnd.nextInt();
            int y = rnd.nextInt();
            int z = rnd.nextInt();
            map2.put(new AddressableTest(x,y,z,x+";"+y+";"+z));
        }
        long time3 = System.currentTimeMillis();
        System.out.println("Put random test results 1: "+(time2-time1));
        System.out.println("Put random test results 2: "+(time3-time2));
        time1 = System.currentTimeMillis();
        for(int i=0;i<320;i++){
            for(AddressableTest test:map1)
                test.getX();
        }
        time2 = System.currentTimeMillis();
        for(int i=0;i<320;i++){
            for(AddressableTest test:map2)
                test.getX();
        }
        time3 = System.currentTimeMillis();
        System.out.println("Iterator test results 1: "+(time2-time1));
        System.out.println("Iterator test results 2: "+(time3-time2));
       
       time1 = System.currentTimeMillis();
        for(int i=0;i<32000;i++){
            map1.remove(rnd.nextInt(), rnd.nextInt(), rnd.nextInt());
        }
        time2 = System.currentTimeMillis();
        for(int i=0;i<32000;i++){
            map2.remove(rnd.nextInt(), rnd.nextInt(), rnd.nextInt());
        }
        time3 = System.currentTimeMillis();
        System.out.println("Remove random test results 1: "+(time2-time1));
        System.out.println("Remove random test results 2: "+(time3-time2));
``
Results of a test:
Put random test results new map: 236 ms
Put random test results old map: 89 ms
Iterator test results new map: 595 ms
Iterator test results old map: 2267 ms
Remove random test results new map: 38 ms
Remove random test results old map: 11 ms

Reproducible with slight deviation.

No bugs occurred during player movement and teleportation.

### CODE REVIEW

**Comment by Foghrye4** [comment]
@Cyclonit you are right about 'getNextPointerIndex'. Done.

**Comment by Niko-sk2x** [comment]
Was it actually a performance issue before?

**Comment by Foghrye4** [comment]
@Barteks2x according build-in profiler there is a performance issue in everything on server tick. This version is just a little bit faster.

**Comment by asiekierka** [comment]
You might want to try benchmarking with JMH instead of manually like this, as JIT warm-up and other statistics can heavily influence results.

**Comment by sirsavary** [comment]
I could possibly write a JMH wrapper if I get time and no one else is able to.

**Comment by Foghrye4** [comment]
[JMH test results](https://github.com/OpenCubicChunks/CubicChunks/files/1142825/results.txt)

>Benchmark                             Mode  Cnt     Score      Error   Units
BuilderBenchmark.getElementNewMap    thrpt   10  5215.819 ± 1359.860  ops/ms
BuilderBenchmark.getElementOldMap    thrpt   10  6675.893 ±  193.700  ops/ms
BuilderBenchmark.iterateElementsNew  thrpt   10    71.671 ±    0.630  ops/ms
BuilderBenchmark.iterateElementsOld  thrpt   10    11.882 ±    0.061  ops/ms

Benchmark code:
```    
@Setup
    public void setup() {
        for(int i=0;i<100;i++){
            new_filled_map.put(new Addressable(i,i,i,String.valueOf(i)));
            old_filled_map.put(new Addressable(i,i,i,String.valueOf(i)));
        }
    }

    @Benchmark
    public void getElementOldMap(Blackhole bh) {
        bh.consume(old_filled_map.get(50, 50, 50));
    }
    
    @Benchmark
    public void getElementNewMap(Blackhole bh) {
        bh.consume(new_filled_map.get(50, 50, 50));
    }

    @Benchmark
    public void iterateElementsOld(Blackhole bh) {
        for(Addressable a:old_filled_map)
            bh.consume(a);
    }

    @Benchmark
    public void iterateElementsNew(Blackhole bh) {
        for(Addressable a:new_filled_map)
            bh.consume(a);
    }
```

Note, that this map included in #244 .
JMH benchmark tests code is not included in PRs.

**Comment by Niko-sk2x** [comment]
Slower `get()` isn't a good thing here. Iteration usually is much less overhead than the get() when doing any block operations. The iterator is I think only used in ChunkGC.

**Comment by Foghrye4** [comment]
@Barteks2x PlayerCubeMap iterate thru 'cubeWatchers' every tick. And latest merged PR by me also add iterator thru all loaded cubes to launch block updates via cube.
We have almost 7x faster iterator and in opposite side only 28% slower `get()`
Also note that `get()` operation is 100x faster that iteration thru 100 elements.

I could make `get()` as fast as in old map, but that would cost speed of `put()` and will double used memory.

**Comment by Niko-sk2x** [comment]
Can you verify that it doesn't noticably affect getBlock/setBlock performance? (just test how much time it takes to get/set a few million blocks or something like that,

**Comment by Foghrye4** [comment]
@Barteks2x hmm... Using JMH? That would be quite hard.

**Comment by Niko-sk2x** [comment]
I wanted to write that you can do it without JMH, in some tick handler. But got distracted while writing and forgot to write that.

**Comment by Foghrye4** [comment]
https://pastebin.com/x0Bzpxyq

Output:

New map

[22:03:05] [Client thread/INFO]: [CHAT] Done 41889
[22:03:06] [Client thread/INFO]: [CHAT] Done 37093
[22:03:07] [Client thread/INFO]: [CHAT] Done 44165
[22:03:08] [Client thread/INFO]: [CHAT] Done 41629
[22:03:09] [Client thread/INFO]: [CHAT] Done 36739
[22:03:10] [Client thread/INFO]: [CHAT] Done 38184
[22:03:11] [Client thread/INFO]: [CHAT] Done 42266
[22:03:12] [Client thread/INFO]: [CHAT] Done 36720
[22:03:13] [Client thread/INFO]: [CHAT] Done 39748
[22:03:13] [Client thread/INFO]: [CHAT] Done 37434
[22:03:14] [Client thread/INFO]: [CHAT] Done 36875
[22:03:15] [Client thread/INFO]: [CHAT] Done 43548
[22:03:21] [Client thread/INFO]: [CHAT] Done 37254
[22:03:36] [Client thread/INFO]: [CHAT] Done 42295
[22:03:44] [Client thread/INFO]: [CHAT] Done 43421
[22:03:50] [Client thread/INFO]: [CHAT] Done 42367

Old (current) map

[22:09:13] [Client thread/INFO]: [CHAT] Done 35675
[22:09:15] [Client thread/INFO]: [CHAT] Done 39516
[22:09:15] [Client thread/INFO]: [CHAT] Done 35603
[22:09:16] [Client thread/INFO]: [CHAT] Done 41300
[22:09:17] [Client thread/INFO]: [CHAT] Done 43516
[22:09:18] [Client thread/INFO]: [CHAT] Done 42174
[22:09:18] [Client thread/INFO]: [CHAT] Done 42147
[22:09:19] [Client thread/INFO]: [CHAT] Done 41719
[22:09:20] [Client thread/INFO]: [CHAT] Done 39640
[22:09:21] [Client thread/INFO]: [CHAT] Done 43342
[22:09:22] [Client thread/INFO]: [CHAT] Done 41101
[22:09:24] [Client thread/INFO]: [CHAT] Done 35606
[22:09:25] [Client thread/INFO]: [CHAT] Done 38720
[22:09:26] [Client thread/INFO]: [CHAT] Done 41619
[22:09:27] [Client thread/INFO]: [CHAT] Done 40749
[22:09:28] [Client thread/INFO]: [CHAT] Done 38411
[22:09:29] [Client thread/INFO]: [CHAT] Done 43211
[22:09:30] [Client thread/INFO]: [CHAT] Done 43323
[22:09:31] [Client thread/INFO]: [CHAT] Done 35576
[22:09:31] [Client thread/INFO]: [CHAT] Done 40416
[22:09:32] [Client thread/INFO]: [CHAT] Done 40355
[22:09:33] [Client thread/INFO]: [CHAT] Done 42376
[22:09:34] [Client thread/INFO]: [CHAT] Done 43537
[22:09:34] [Client thread/INFO]: [CHAT] Done 38349
[22:09:35] [Client thread/INFO]: [CHAT] Done 40484

BTW you are using column and XZMap to get block state. XYZMap unrelated to `getBlockState()` function.

**Comment by Niko-sk2x** [comment]
I'm using **both** to get BlockState. Look into the Chunk mixins.

**Comment by Foghrye4** [comment]
Huh, sorry, I missed that. Well, next PR will be for using cubes directly.

**Comment by Niko-sk2x** [comment]
That's not going to work, because cubes don't have the needed methods. I specifically removed the to prevent code duplication. Cubes are  supposed to be basically like ExtendedBlockStorage, but with entity and tile entity data included.

**Comment by Niko-sk2x** [comment]
Merging it for now. If it breaks anything, it will be reverted.

**Comment by Foghrye4** [comment]
And now #244 have merge conflict... what about #244? Leave it or rebase it?

**Comment by Niko-sk2x** [comment]
Reverted because it caused crashes and I don't feel like debugging it further myself. Here is all you need to know to debug it:

Code used to test it:
```java
import cubicchunks.util.CubePos;
import cubicchunks.util.XYZAddressable;
import cubicchunks.util.XYZMap;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class XYZMapReplay {
    public static void main(String... args) throws Throwable {
        File file = new File("location/of/the/text/file");
        XYZMap<XYZAddressable> map = new XYZMap<>(0.7f, 8000);
        Map<CubePos, XYZAddressable> m = new HashMap<>();
        int i = 0;
        try (Scanner sc = new Scanner(file)) {
            while(sc.hasNext()) {
                String mode = sc.next();
                int x = sc.nextInt();
                int y = sc.nextInt();
                int z = sc.nextInt();
                sc.nextLine(;
                if (mode.contains("A")) {
                    XYZAddressable a = new XYZAddressable() {
                        @Override public int getX() { return x; }
                        @Override public int getY() { return y; }
                        @Override public int getZ() { return z; }};
                    map.put(a);
                    m.put(new CubePos(x, y, z), a);
                } else {
                    map.remove(x, y, z);
                    m.remove(new CubePos(x, y, z));
                }
                for (CubePos p : m.keySet()) {
                    if (!map.contains(p.getX(), p.getY(), p.getZ())) {
                        throw new Error(String.valueOf(i));
                    }
                }
                i++;
            }
        }
    }
}
```

And the data used:
[DEBUG.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1150673/DEBUG.txt)

This crashes when comparing XYZMap contents with HashMap contents, so XYZMap must be wrong.

**Comment by Niko-sk2x** [comment]
@Foghrye4 Can you fix it?

**Comment by Foghrye4** [comment]
@Barteks2x Will try.

**Pull request merged**
